### ISSUE TITLE
java.lang.NoClassDefFoundError when running tests

### ISSUE THREAD

**Issue by michaelmior** [mitdbg/aurum-datadiscovery#133]
Currently several tests fail for me.

```
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:test

test.RangeAnalyzerTest > RangeTest FAILED
    java.lang.NoClassDefFoundError at RangeAnalyzerTest.java:29
        Caused by: java.lang.ClassNotFoundException at RangeAnalyzerTest.java:29

test.TestOfflineMode > offlineModeTest FAILED
    java.lang.NoClassDefFoundError at TestOfflineMode.java:28

test.AnalyzerTest > test FAILED
    java.lang.NoClassDefFoundError at AnalyzerTest.java:47

test.AlmostE2ETest > almostE2ETestDB FAILED
    java.lang.NoClassDefFoundError at AlmostE2ETest.java:59

test.StoreLoadingTest > storeLoadingE2ETest FAILED
    java.lang.NoClassDefFoundError at StoreLoadingTest.java:30

test.PreAnalyzerTest > testRegExpPerformance FAILED
    java.lang.NoClassDefFoundError at PreAnalyzerTest.java:85

test.PreAnalyzerTest > testPreAnalyzerForTypesCSVFile FAILED
    java.lang.NoClassDefFoundError at PreAnalyzerTest.java:127

test.PreAnalyzerTest > testPreAnalyzerForTypesDB FAILED
    java.lang.NoClassDefFoundError at PreAnalyzerTest.java:144

test.performance.JustReadTest > test FAILED
    java.lang.NoClassDefFoundError at JustReadTest.java:29
:test FAILED
4 actionable tasks: 1 executed, 3 up-to-date
```

An example stack trace from one of the failures is below:

```
java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at core.config.Config.<init>(Config.java:24)
	at core.config.ProfilerConfig.<init>(ProfilerConfig.java:77)
	at test.performance.JustReadTest.test(JustReadTest.java:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by raulcf** [comment]
Thanks! The current test suite is not up to date. To try out the system I recommend you following the instructions in the readme, grade will skip tests to avoid this issue. Also, the most up-to-date version of this software in the fork on raulcf/aurum-datadiscovery (https://github.com/raulcf/aurum-datadiscovery).

**Comment by michaelmior** [comment]
I was interested in adding another data source. The main reason I was hoping to get tests working was so I could add tests for my own code. I'll try the fork :)

**Comment by raulcf** [comment]
Makes sense. We're building a new iteration of a data discovery system and
will be open sourcing the code soon, so a lot of resources have shifted,
but happy to help debug, etc.
Raul

**Comment by michaelmior** [comment]
Looks like I'm still getting failing tests in that fork unfortunately. But I'll see if I can make some progress :) However, depending on when the "soon" is, maybe it would be easier for me to wait.
